/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ca924a78-5a3a-464b-8104-b17080ad17b2",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_yEkcE8h5j",
    "aws_user_pools_web_client_id": "75iuap23l4ti8aosn26rneskqd",
    "oauth": {}
};


export default awsmobile;
